{"wrong_code": "fn main() {\n    call_me(3);\n}\n\nfn call_me(num: int) {\n    for i in 0..num {\n        println!(\"Ring! Call number {}\", i + 1);\n    }\n}", "error": "error[E0412]: cannot find type `int` in this scope\n --> exercises/functions/functions2.rs:8:17\n  |\n8 | fn call_me(num: int) {\n  |                 ^^^\n  |                 |\n  |                 not found in this scope\n  |                 help: perhaps you intended to use this type: `i32`\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0412`.", "right_code": "fn main() {\n    call_me(3);\n}\n\nfn call_me(num: i32) {\n    for i in 0..num {\n        println!(\"Ring! Call number {}\", i + 1);\n    }\n}"}
